"""initial migration

Revision ID: 68f0ab12ddc9
Revises: 
Create Date: 2023-09-10 05:14:45.252318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f0ab12ddc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_url', sa.String(length=36), nullable=False),
    sa.Column('activated_on', sa.DateTime(), nullable=True),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_url')
    )
    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_activated_on'), ['activated_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_last_accessed'), ['last_accessed'], unique=False)

    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_timestamp'), ['timestamp'], unique=False)

    op.create_table('post_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_request_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_request_timestamp'))

    op.drop_table('post_request')
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_timestamp'))

    op.drop_table('data')
    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_last_accessed'))
        batch_op.drop_index(batch_op.f('ix_panel_expires_on'))
        batch_op.drop_index(batch_op.f('ix_panel_activated_on'))

    op.drop_table('panel')
    op.drop_table('user')
    # ### end Alembic commands ###
